version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/run
          name: Chrome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          browser: chrome
          spec: cypress/e2e/05-assertions.cy.js
